# Generated by Django 5.2.3 on 2025-06-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JuegoNintendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('anio_lanzamiento', models.IntegerField()),
                ('resena', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JuegoPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('anio_lanzamiento', models.IntegerField()),
                ('resena', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JuegoSony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('anio_lanzamiento', models.IntegerField()),
                ('resena', models.TextField()),
            ],
        ),
    ]
