# Generated by Django 5.2.3 on 2025-06-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_Juegos', '0002_rename_anio_lanzamiento_juegonintendo_lanzamiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juegonintendo',
            old_name='resena',
            new_name='reseña',
        ),
        migrations.RenameField(
            model_name='juegopc',
            old_name='resena',
            new_name='reseña',
        ),
        migrations.RenameField(
            model_name='juegosony',
            old_name='resena',
            new_name='reseña',
        ),
    ]
