# Generated by Django 5.2.3 on 2025-06-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_Juegos', '0003_rename_resena_juegonintendo_reseña_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegonintendo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='juegos_nintendo/'),
        ),
        migrations.AddField(
            model_name='juegopc',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='juegos_pc/'),
        ),
        migrations.AddField(
            model_name='juegosony',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='juegos_sony/'),
        ),
    ]
