# Generated by Django 5.2.3 on 2025-06-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_Juegos', '0004_juegonintendo_imagen_juegopc_imagen_juegosony_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegonintendo',
            name='origen',
            field=models.CharField(default='Juego Nintendo', max_length=20),
        ),
        migrations.AddField(
            model_name='juegopc',
            name='origen',
            field=models.CharField(default='Juego PC', max_length=20),
        ),
        migrations.AddField(
            model_name='juegosony',
            name='origen',
            field=models.CharField(default='Juego Sony', max_length=20),
        ),
    ]
