# Generated by Django 5.2.3 on 2025-06-17 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca_Juegos', '0005_juegonintendo_origen_juegopc_origen_juegosony_origen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juegonintendo',
            old_name='origen',
            new_name='consola',
        ),
        migrations.RenameField(
            model_name='juegopc',
            old_name='origen',
            new_name='consola',
        ),
        migrations.RenameField(
            model_name='juegosony',
            old_name='origen',
            new_name='consola',
        ),
    ]
